# 워크플로우의 이름을 지정합니다.
name: Node.js CI

# 워크플로우가 트리거될 이벤트를 지정합니다.
# 여기서는 'push' 이벤트가 'main' 브랜치에서 발생할 때 실행됩니다.
on:
  push:
    branches: [ main ]

# 워크플로우에 포함된 작업(jobs)을 정의합니다.
jobs:
  # 'build'라는 이름의 단일 작업을 정의합니다.
  build:
    # 작업이 실행될 환경을 지정합니다.
    runs-on: ubuntu-latest

    # 매트릭스 전략을 사용하여 여러 버전의 Node.js에서 테스트를 실행합니다.
    strategy:
      matrix:
        node-version: [24.x]

    # 'build' 작업에 포함된 단계(steps)를 정의합니다.
    steps:
      # 1. 'checkout' 액션을 사용하여 리포지토리를 체크아웃합니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 'setup-node' 액션을 사용하여 Node.js 환경을 설정합니다.
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. 'npm install' 명령어를 실행하여 의존성을 설치합니다.
      - name: Install dependencies
        run: npm install

      # 4. 'npm test' 명령어를 실행하여 테스트를 수행합니다.
      - name: Run tests
        run: npm test
